[package]
name = "sloth-compile"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
infra = { path = "../../lib/infra" }
serde_json = "1"
sloth = { path = "../../lib/sloth" }
