
pull_request_rules:
  - name: dependabot + merge
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from dependabot
    queue_conditions:
      - author=dependabot[bot]
    merge_conditions: []
    merge_method: squash
  - name: duplicated default from merge
    queue_conditions:
      - label=merge
      - or:
          - author=raviqqe
          - "#approved-reviews-by>=1"
    merge_conditions: []
    merge_method: squash
  - name: default
    conditions: []
