[package]
name = "falco"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.17.0"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.17.0"
