version: 2
jobs:
  build:
    docker:
      - image: einlang/ci
    steps:
      - checkout
      - run: npx cspell '**/*.{feature,md,rs}'
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo audit
      - run: cargo test --lib
      - run: cargo build --release --package runtime
      - run: EIN_ROOT=$PWD PATH=$PWD/target/debug:$PATH cucumber
