version: 2
jobs:
  build:
    docker:
      - image: einlang/ci
    steps:
      - checkout
      - run: npx cspell '**/*.{feature,md,rs}'
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo audit
      - run: cargo test
      - run: cargo build --release
      - run: EIN_ROOT=$PWD PATH=$PWD/target/release:$PATH cucumber
