version: 2
workflows:
  version: 2
  test:
    jobs:
      - test
      - coverage
jobs:
  test:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run: |
          pacman -Syu --noconfirm base-devel clang llvm npm ruby-bundler rustup
          rustup default stable
          rustup component add clippy rustfmt
          bundler install
          npm install -g cspell
      - run: cspell '**/*.{feature,md,rs}'
      - run: cargo build
      - run: cargo clippy -- -D warnings
      - run: cargo fmt -- --check
      - run: cargo test
      - run: |
          cargo build --release
          EIN_ROOT=$PWD PATH=$PWD/target/release:$PATH bundler exec cucumber
  coverage:
    machine: true
    steps:
      - checkout
      - run: docker run --security-opt seccomp=unconfined -v $PWD:/volume xd009642/tarpaulin /bin/sh -c 'apt -y update --fix-missing && apt -y install cmake libssl-dev lsb-release pkg-config software-properties-common zlib1g-dev && wget -O - https://apt.llvm.org/llvm.sh | bash /dev/stdin 8 && cargo tarpaulin'
