[package]
name = "ein"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
app = { path = "../../lib/app" }
clap = "2"
lang = { path = "../../lib/lang" }
infra = { path = "../../lib/infra" }
lazy_static = "1"
