[package]
name = "compiler"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
core = { path = "../../lib/core" }
indoc = "0.3"
nom = "5"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
