name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: einlang/ci
    env:
      HOME: /root
      RUST_MIN_STACK: 8388608
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo build (runtime)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package runtime
      - run: EIN_ROOT=$PWD PATH=$PWD/target/debug:$PATH cucumber
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx cspell '**/*.{feature,md,rs}'
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - run: curl -f https://apt.llvm.org/llvm.sh | sudo bash /dev/stdin 10
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast -- --test-threads=1
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"
      - id: coverage
        uses: actions-rs/grcov@v0.1
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ steps.coverage.outputs.report }}
