name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: einlang/ci
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: npx cspell '**/*.{feature,md,rs}'
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo build --release
      - run: EIN_ROOT=$PWD PATH=$PWD/target/release:$PATH cucumber
