name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: einlang/ci
    env:
      HOME: /root
      JOBS: 8
    steps:
      - uses: actions/checkout@master
      - run: npx cspell '**/*.{feature,md,rs}'
      - run: cargo build -j $JOBS
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo audit
      - run: cargo test -j $JOBS
      - run: cargo build --release --package runtime
      - run: EIN_ROOT=$PWD PATH=$PWD/target/debug:$PATH cucumber
