name: test
on:
  - push
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: raviqqe/enable-homebrew@main
      - run: tools/ci/setup.sh
      - run: cargo test
        env:
          RUST_MIN_STACK: 8388608
  integration-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: raviqqe/enable-homebrew@main
      - run: tools/ci/setup.sh
      - uses: ruby/setup-ruby@v1
      - run: sudo apt update --fix-missing
      - run: sudo apt install clang valgrind
      - run: tools/integration_test.sh
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: raviqqe/enable-homebrew@main
      - run: tools/ci/setup.sh
      - run: cargo clippy -- -D warnings
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{feature,md,rs}"
