name: test
on:
  - push
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/ci/setup.sh
      - run: cargo test
        env:
          RUST_MIN_STACK: 8388608
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/ci/setup.sh
      - run: sudo apt update --fix-missing
      - run: sudo apt install clang valgrind
      - run: tools/integration_test.sh
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: homebrew/actions/setup-homebrew@master
      - run: tools/ci/setup.sh
      - run: cargo clippy -- -D warnings
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@main
        with:
          files: "**/*.{feature,md,rs}"
  test:
    needs:
      - unit_test
      - integration_test
      - format
      - lint
      - spell_check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
