name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: archlinux/base
    steps:
      - uses: actions/checkout@v1
      - run: |
          pacman -Syu --noconfirm base-devel clang llvm npm ruby-bundler rustup
          rustup default stable
          rustup component add clippy rustfmt
          bundler install
          npm install -g cspell
      - run: cargo build
      - run: npx cspell '**/*.{feature,md,rs}'
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
      - run: cargo build --release
      - run: EIN_ROOT=$PWD PATH=$PWD/target/release:$PATH cucumber
